/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import main.Graph;
import main.Product;

/**
 *
 * @author mdetd
 */
public class stockManagementPage extends javax.swing.JFrame {

    String storage = "";
    Product[] inv;
    Graph g1;
    String product = "";
    int quantity = 0;

    /**
     * Creates new form stockManagementPage
     */
    public stockManagementPage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        productChooserCombo1.setEnabled(false);
        selectProductButton.setEnabled(false);
        unitsExistingProductTextField.setEnabled(false);
        selectUnitsButton.setEnabled(false);
        addQuantityButton.setEnabled(false);

    }

    private void defaultValues() {
        productChooserCombo1.setEnabled(false);
        selectProductButton.setEnabled(false);
        unitsExistingProductTextField.setEnabled(false);
        selectUnitsButton.setEnabled(false);
        addQuantityButton.setEnabled(false);
        productChooserCombo1.removeAllItems();
        unitsExistingProductTextField.setText("");
        actualQuantityLabel.setText("");
        newQuantityLabel.setText("");
    }

    public void fillProductsCombo() {
        productChooserCombo1.removeAllItems();
        inv = g1.getStorageList().getStorageByName(storage).getInventory().getProductStringArray();
        for (int i = 0; i < inv.length; i++) {
            productChooserCombo1.addItem(inv[i].getName());

        }

    }

    public void fillTransmitterChooserCombo(Graph g1) {
        storageChooserCombo.removeAllItems();
        String[] storages = g1.namenOnAString();
        for (int i = 0; i < storages.length; i++) {
            storageChooserCombo.addItem(storages[i]);
        }
    }

    public void setGraph(Graph graph) {
        g1 = graph;
        fillTransmitterChooserCombo(g1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteButton1 = new javax.swing.JButton();
        addQuantityButton1 = new javax.swing.JButton();
        newQuantityNumberTitleLabel = new javax.swing.JLabel();
        newQuantityTitleLabel2 = new javax.swing.JLabel();
        selectQuantityTitleLabel1 = new javax.swing.JLabel();
        unitsNewProductTextField = new javax.swing.JTextField();
        selectNewUnitsButton = new javax.swing.JButton();
        newQuantityTitleLabel = new javax.swing.JLabel();
        newQuantityLabel = new javax.swing.JLabel();
        selectProductButton = new javax.swing.JButton();
        productChooserCombo1 = new javax.swing.JComboBox<>();
        storageChooserCombo = new javax.swing.JComboBox<>();
        selectProductQuantityLabel3 = new javax.swing.JLabel();
        selectStorageButton = new javax.swing.JButton();
        unitsExistingProductTextField = new javax.swing.JTextField();
        selectUnitsButton = new javax.swing.JButton();
        addQuantityButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        actualQuantityTitleLabel = new javax.swing.JLabel();
        actualQuantityLabel = new javax.swing.JLabel();
        selectQuantityTitleLabel = new javax.swing.JLabel();
        selectStorageTitleLabel = new javax.swing.JLabel();
        selectProductQuantityLabel = new javax.swing.JLabel();
        selectProductQuantityLabel1 = new javax.swing.JLabel();
        selectProductQuantityLabel2 = new javax.swing.JLabel();
        selectNewProductNameButton = new javax.swing.JButton();
        newProductNameTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButton1.setText("Borrar");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 90, 40));

        addQuantityButton1.setText("Agregar");
        addQuantityButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuantityButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(addQuantityButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 90, 40));

        newQuantityNumberTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(newQuantityNumberTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 120, -1));

        newQuantityTitleLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newQuantityTitleLabel2.setText("Cantidad:");
        jPanel1.add(newQuantityTitleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        selectQuantityTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectQuantityTitleLabel1.setText("Seleccione cantidad:");
        jPanel1.add(selectQuantityTitleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));
        jPanel1.add(unitsNewProductTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 200, -1));

        selectNewUnitsButton.setText("Seleccionar");
        selectNewUnitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNewUnitsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectNewUnitsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 200, -1));

        newQuantityTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newQuantityTitleLabel.setText("Cantidad nueva:");
        jPanel1.add(newQuantityTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        newQuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(newQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 80, -1));

        selectProductButton.setText("Seleccionar");
        selectProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 220, -1));

        jPanel1.add(productChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 220, -1));

        jPanel1.add(storageChooserCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, -1));

        selectProductQuantityLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectProductQuantityLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectProductQuantityLabel3.setText("Agregar nuevo producto al inventario");
        jPanel1.add(selectProductQuantityLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 380, -1));

        selectStorageButton.setText("Seleccionar");
        selectStorageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStorageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectStorageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, -1));
        jPanel1.add(unitsExistingProductTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 220, -1));

        selectUnitsButton.setText("Seleccionar");
        selectUnitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUnitsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectUnitsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 220, -1));

        addQuantityButton.setText("Agregar");
        addQuantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuantityButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addQuantityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 90, 40));

        deleteButton.setText("Borrar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 90, 40));

        actualQuantityTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualQuantityTitleLabel.setText("Cantidad actual:");
        jPanel1.add(actualQuantityTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        actualQuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(actualQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 80, -1));

        selectQuantityTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectQuantityTitleLabel.setText("Seleccione cantidad:");
        jPanel1.add(selectQuantityTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        selectStorageTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectStorageTitleLabel.setText("Seleccione el almacén");
        jPanel1.add(selectStorageTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        selectProductQuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectProductQuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectProductQuantityLabel.setText("Agregar unidades a producto ya existente");
        jPanel1.add(selectProductQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 380, -1));

        selectProductQuantityLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectProductQuantityLabel1.setText("Seleccione el producto");
        jPanel1.add(selectProductQuantityLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        selectProductQuantityLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectProductQuantityLabel2.setText("Nombre producto nuevo");
        jPanel1.add(selectProductQuantityLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        selectNewProductNameButton.setText("Seleccionar");
        selectNewProductNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNewProductNameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectNewProductNameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 200, -1));
        jPanel1.add(newProductNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectStorageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStorageButtonActionPerformed
        storage = storageChooserCombo.getSelectedItem().toString();
        fillProductsCombo();
        productChooserCombo1.setEnabled(true);
        selectProductButton.setEnabled(true);
        unitsExistingProductTextField.setEnabled(true);
        selectUnitsButton.setEnabled(true);


    }//GEN-LAST:event_selectStorageButtonActionPerformed

    private void selectProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProductButtonActionPerformed
        product = productChooserCombo1.getSelectedItem().toString();
        quantity = g1.getStorageList().getStorageByName(storage).getInventory().getProductByName(product).getQuantity();
        actualQuantityLabel.setText(String.valueOf(quantity));
        newQuantityLabel.setText(String.valueOf(quantity));


    }//GEN-LAST:event_selectProductButtonActionPerformed

    private void selectUnitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUnitsButtonActionPerformed
        String stQuantity = unitsExistingProductTextField.getText();

        if (InterfaceFunctions.isANumber(stQuantity)) {
            int quant = Integer.parseInt(stQuantity);
            if (quant > 0) {
                quantity += quant;
                newQuantityLabel.setText(String.valueOf(quantity));

                addQuantityButton.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
                unitsExistingProductTextField.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
            unitsExistingProductTextField.setText("");
        }
    }//GEN-LAST:event_selectUnitsButtonActionPerformed

    private void addQuantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuantityButtonActionPerformed
        g1.getStorageList().getStorageByName(storage).getInventory().getProductByName(product).setQuantity(quantity);
        defaultValues();

    }//GEN-LAST:event_addQuantityButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        defaultValues();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void selectNewProductNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNewProductNameButtonActionPerformed
        product = newProductNameTextField1.getText();
        product = product.replace(" ", "");
        product = product.replace(";", "");
        product = product.replace(":", "");
        product = product.replace(",", "");
        boolean aux= true;
        
        for (int i = 0; i < inv.length; i++) {
            if (inv[i].getName().equals(product)) {
                aux = false;
                JOptionPane.showMessageDialog(null, "El producto ya existe");
            }
            
        }
        
        if(aux){
            unitsNewProductTextField.setEnabled(true);
            selectNewUnitsButton.setEnabled(true);
            
        }
        
        
    }//GEN-LAST:event_selectNewProductNameButtonActionPerformed

    private void selectNewUnitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNewUnitsButtonActionPerformed
        String quant = unitsNewProductTextField.getText();
        if (InterfaceFunctions.isANumber(quant)) {
            if (Integer.parseInt(quant)>0) {
                quantity = Integer.parseInt(quant);
                newQuantityNumberTitleLabel.setText(quant);
            }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un numero valido");
        }
    }//GEN-LAST:event_selectNewUnitsButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void addQuantityButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuantityButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addQuantityButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockManagementPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualQuantityLabel;
    private javax.swing.JLabel actualQuantityTitleLabel;
    private javax.swing.JButton addQuantityButton;
    private javax.swing.JButton addQuantityButton1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newProductNameTextField1;
    private javax.swing.JLabel newQuantityLabel;
    private javax.swing.JLabel newQuantityNumberTitleLabel;
    private javax.swing.JLabel newQuantityTitleLabel;
    private javax.swing.JLabel newQuantityTitleLabel2;
    private javax.swing.JComboBox<String> productChooserCombo1;
    private javax.swing.JButton selectNewProductNameButton;
    private javax.swing.JButton selectNewUnitsButton;
    private javax.swing.JButton selectProductButton;
    private javax.swing.JLabel selectProductQuantityLabel;
    private javax.swing.JLabel selectProductQuantityLabel1;
    private javax.swing.JLabel selectProductQuantityLabel2;
    private javax.swing.JLabel selectProductQuantityLabel3;
    private javax.swing.JLabel selectQuantityTitleLabel;
    private javax.swing.JLabel selectQuantityTitleLabel1;
    private javax.swing.JButton selectStorageButton;
    private javax.swing.JLabel selectStorageTitleLabel;
    private javax.swing.JButton selectUnitsButton;
    private javax.swing.JComboBox<String> storageChooserCombo;
    private javax.swing.JTextField unitsExistingProductTextField;
    private javax.swing.JTextField unitsNewProductTextField;
    // End of variables declaration//GEN-END:variables
}
